# Accelerate display bring-up by preloading all display related modules during boot
# using systemd-modules-load.service.

# Below modules are loaded early to avoid the usual latency in the udev coldplug
# flow and makes display card0 available sooner.

# This configuration file is placed in '/etc/modules-load.d/'
# This file is meant for machine : 'iq-9075-evk'

display_connector
gpucc_sa8775p
dispcc0_sa8775p
msm
typec
