# Kernel modules for quick boot display/GPU bring-up, loaded via
# systemd-modules-load.service (modules-load.d). Loading them explicitly at
# boot accelerates display bring-up.

mdt_loader
drm_kms_helper
socinfo
display_connector
gpucc_sa8775p
dispcc1_sa8775p
llcc_qcom
gpi
dispcc0_sa8775p
drm_dp_aux_bus
drm_display_helper
gpu_sched
msm
typec
phy_qcom_edp
