# Accelerate audio bring-up by preloading all audio related modules during boot
# using systemd-modules-load.service.

# This below modules list avoids the usual latency in the udev coldplug flow and
# makes /dev/soundcontrolC0 available sooner.

# This configuration file is placed in '/etc/modules-load.d/'
# This file is common for all machines

qrtr-smd
rpmsg_ctrl
qcom_q6v5_pas
fastrpc
snd-soc-dmic
snd-soc-max98357a
snd-soc-hdmi-codec
q6apm-dai
q6apm-lpass-dais
snd-soc-sc8280xp
