# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Allow weston user to access FastRPC and DMA-HEAP devices

[Service]
SupplementaryGroups=fastrpc dmaheap
