name: Build on PR
run-name: "${{ github.base_ref }}: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches:
      - main
      - wrynose
    paths-ignore:
      - 'README.md'
      - 'README'
      - 'SECURITY.md'

permissions:
  contents: read

jobs:
  event-file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: Event File
        path: ${{ github.event_path }}

  pr-to-workflow-dependency:
    name: "PR To Workflow Dependency"
    permissions:
      actions: read
      contents: read
      pull-requests: read
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/qswat-reusable-pr-to-workflow-dependency.yml@qswat-release-v1
    with:
      workflow_id: ${{ github.run_id }}
      run_attempt: ${{ github.run_attempt }}
      pr_number: ${{ github.event.pull_request.number }}

  build-pr:
    permissions:
      contents: read
      packages: read
      actions: read
    uses: ./.github/workflows/build-yocto.yml
    with:
      profile: pr

