name: Build on push

on:
  push:
    branches:
      - main
      - next
      - wrynose

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      packages: read
      actions: read
    uses: ./.github/workflows/build-yocto.yml
  test:
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/test.yml
    needs: [build]
    secrets: inherit
    with:
      build_id: ${{ github.run_id }}
  publish-test-results:
    permissions:
      contents: read
      packages: read
      actions: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/publish-results.yml
    needs: test
    secrets: inherit
    with:
      workflow_id: ${{ github.run_id }}
      event_name: ${{ github.event_name }}
      event_file: ${{ github.event_path }}
      commit: ${{ github.sha }}
