name: Weekly Build

on:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 3:00 AM UTC
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  build-weekly:
    uses: ./.github/workflows/build-yocto.yml
    with:
      profile: weekly
